name: Production

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  NODE_VERSION: "12.19"
  TERRAFORM_VERSION: 0.14.2
  AZURE_WEBAPP_PACKAGE_PATH: './webapp'
  RG_NAME: <Production Resource Group Name>
  PREFIX: <Resource Prefix>
  WEBAPP_NAME: <Web App Name>

jobs:
  terraform:
    name: 'Terraform'
    environment:
      name: Production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        shell: bash
        run: |
          terraform init \
            -backend-config=resource_group_name=${{ secrets.TERRAFORM_BACKEND_RGNAME }} \
            -backend-config=storage_account_name=${{ secrets.TERRAFORM_BACKEND_SA }} \
            -backend-config=container_name=${{ secrets.TERRAFORM_BACKEND_CNT }} \
            -backend-config=key=${{ secrets.TERRAFORM_BACKEND_KEY }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: |
          terraform plan \
              -var 'resource_group=${{env.RG_NAME}}' \
              -var 'webapp_name=${{env.WEBAPP_NAME}}'

      - name: Terraform Apply
        run: |
          terraform apply --auto-approve  \
              -var 'resource_group=${{env.RG_NAME}}'  \
              -var 'webapp_name=${{env.WEBAPP_NAME}}'

  node:
    needs: [terraform]
    environment:
      name: Production
    runs-on: ubuntu-latest
    name: "Node"
    steps:
      - uses: actions/checkout@v2
      - name: "azure login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: "Deploy to Azure WebApp"
        id: deploy_web_app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.WEBAPP_NAME}}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: logout
        run: |
          az logout
